name: '▶️ Cursor Invoke'

on:
  workflow_call:
    inputs:
      additional_context:
        type: 'string'
        description: 'Any additional context from the request'
        required: false

concurrency:
  group: '${{ github.workflow }}-invoke-${{ github.event_name }}-${{ github.event.pull_request.number || github.event.issue.number }}'
  cancel-in-progress: false

defaults:
  run:
    shell: 'bash'

jobs:
  invoke:
    runs-on: 'ubuntu-latest'
    environment: cursor-env
    permissions:
      contents: 'read'
      id-token: 'write'
      issues: 'write'
      pull-requests: 'write'
    steps:
      - name: 'Mint identity token'
        id: 'mint_identity_token'
        if: |-
          ${{ vars.APP_ID }}
        uses: 'actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b' # ratchet:actions/create-github-app-token@v2
        with:
          app-id: '${{ vars.APP_ID }}'
          private-key: '${{ secrets.APP_PRIVATE_KEY }}'
          permission-contents: 'read'
          permission-issues: 'write'
          permission-pull-requests: 'write'

      - name: 'Install Cursor CLI'
        run: |
          curl https://cursor.com/install -fsS | bash
          echo "$HOME/.cursor/bin" >> $GITHUB_PATH

      - name: 'Run Cursor CLI'
        id: 'run_cursor'
        env:
          CURSOR_API_KEY: '${{ secrets.CURSOR_API_KEY }}'
          GITHUB_TOKEN: '${{ steps.mint_identity_token.outputs.token || secrets.GITHUB_TOKEN || github.token }}'
          TITLE: '${{ github.event.pull_request.title || github.event.issue.title }}'
          DESCRIPTION: '${{ github.event.pull_request.body || github.event.issue.body }}'
          EVENT_NAME: '${{ github.event_name }}'
          IS_PULL_REQUEST: '${{ !!github.event.pull_request }}'
          ISSUE_NUMBER: '${{ github.event.pull_request.number || github.event.issue.number }}'
          REPOSITORY: '${{ github.repository }}'
          ADDITIONAL_CONTEXT: '${{ inputs.additional_context }}'
        run: |
          cursor-agent -p "You have full access to git, GitHub CLI (gh), and PR operations.
          Handle the request for issue/PR #${ISSUE_NUMBER} in repository ${REPOSITORY}.
          Title: ${TITLE}
          Body: ${DESCRIPTION}
          Event: ${EVENT_NAME}
          Is Pull Request: ${IS_PULL_REQUEST}
          Additional context: ${ADDITIONAL_CONTEXT}

          You are an autonomous AI software engineering agent operating within GitHub Actions.
          Analyze the request, plan your approach, execute the necessary actions, and report results.
          Use GitHub CLI commands for all GitHub interactions.
          You have full autonomy to handle commits, pushes, PR comments, and other operations."
